version: '3'
services:
  redis: 
      image: "redis"
      ports: 
        - "6379:6379"
  
  mysql:
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_HOST='%'
      - MYSQL_ROOT_PASSWORD='123456'
      - MYSQL_DATABASE='mysql'

    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
   
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql:db
    # environment:
      # PMA_HOST: mysql
      # PMA_PORT: 3306
      # PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
volumes:
  db:
    