version: '3'
services:
  redis: 
      image: "redis"
      ports: 
        - "6379:6379"
      command: redis-server --maxmemory-policy volatile-lru --maxmemory 4G
  
  mysql:
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=URL_SHORTENER
      - MYSQL_ROOT_HOST=%
    ports:
      - '3306:3306'
    volumes:
      - ~/Workspace/mysql-data:/var/lib/URL_SHORTENER
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "mysql"]
            timeout: 5s
            retries: 10
   
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    depends_on:
      - mysql
    links:
      - mysql:db
    # environment:
      # PMA_HOST: mysql
      # PMA_PORT: 3306
      # PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
  
#   server:
#     depends_on:
#       mysql:
#         condition: service_healthy
#       redis:
#         condition: service_started
#     build: .
#     restart: unless-stopped
#     environment:
#       - PORT=8080
#       - DOMAIN=http://localhost:8080/
#       - MAX_REQUEST=10
#       - LIMITER_EXPIRE=1
#       - DB_HOST=mysql
#       - DB_USER=root
#       - DB_PASSWORD=123456
#       - DB_PORT=3306
#       - DB_DATABASE=URL_SHORTENER
#       - REDIS_HOST=redis
#       - REDIS_PORT=6379
#       - REDIS_PASSWORD=
  
#     ports:
#       - '8080:8080'
# volumes:
#   db: 
    