SET GLOBAL time_zone = '+07:00';
SET @@global.time_zone = '+07:00';
USE URL_SHORTENER;
CREATE TABLE IF NOT EXISTS URL (
    ID BIGINT PRIMARY KEY,
    USER VARCHAR(500),
    SHORT_URL VARCHAR(500),
    LONG_URL VARCHAR(500),
    EXPIRE_TIME TIMESTAMP
);
ALTER TABLE URL
ADD INDEX INDEX_ID USING BTREE (ID);
ALTER TABLE URL
ADD INDEX INDEX_SHORT_URL USING HASH (SHORT_URL);
ALTER TABLE URL
ADD INDEX INDEX_LONG_URL USING HASH (LONG_URL);

SET GLOBAL event_scheduler = ON;
CREATE EVENT IF NOT EXISTS URL_SHORTENER.DELETE_EXPIRED_URL ON SCHEDULE EVERY 1 DAY 
DO DELETE FROM URL_SHORTENER.URL WHERE EXPIRE_TIME < NOW();
