[database]
    host        = "mysql"
    port        = "3306"   
    user        = "root"
    password    = "123456"
    database    = "URL_SHORTENER"

[redis]
    host        = "redis"
    port        = "6379"
    password    = ""

[server]
    port        = "8080"

[limitter]
    max_request     = "10000"
    limitter_expire = "1"