[database]
    host                = "10.11.166.7"
    port                = "32094"
    user                = "ekyc_dev"
    password            = "KxWnXU9x3f5zJpcwbDkUkjDS68E2nURFp5n9"
    database            = "video_call"
    max_open_connection = "100"
    max_idle_connection = "20"

[redis]
    address             = "10.109.1.9:50044"
    # Split address by COMMA, Example: address = "0.0.0.0:6379, 0.0.0.0:6379" 
    password            = "trueidpass"
    database            = "0"
    is_cluster          = "true"

[app]
    port                = "80"
[limitter]
    max_request         = "100000"
    limitter_expire     = "1"

[logger]
    level = "info"
    filePath= "./logs/shorten_url"
    maxSize=1
    maxBackups=10
    maxAge=28
    sentry_url = ""

[view]
    path                = "./view"

[key]
    secret = "Secret key: !@#$%^&*()432144adsfdsafhk12312532dfhsajkfghjkg732478321er1234hkjdhf78234h"